version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: namebot_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: namebot_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./sessions:/app/sessions
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: